PDF - Probibility density function

In [5]:
from scipy.stats import norm
import numpy as np

In [3]:
# Find prob-density of 0 from standard normal distribution
norm.pdf(0)

0.3989422804014327

In [4]:
# If mean other than 0 and variance other than 1
# scale = standard deviation not variance, this is a variance of 100
norm.pdf(0, loc=5, scale=10)

0.035206532676429952

In [6]:
# Calculate PDF of values in an array
# Do not use for loop for this
r = np.random.randn(10)
norm.pdf(r)

array([ 0.13036934,  0.37740014,  0.36038916,  0.39670057,  0.28489517,
        0.3961379 ,  0.36043476,  0.29277486,  0.35052568,  0.25041575])

In [7]:
# Common calculation is log of PDF 
# Joint probibility needs multiplication
# Joint log needs addition (and faster)
norm.logpdf(r)

array([-2.03738381, -0.97444927, -1.02057084, -0.92457351, -1.25563397,
       -0.92599289, -1.0204443 , -1.22835137, -1.04832132, -1.38463274])

Cummulative distribution function - Integratal of PDF and is not solvable (no mathmatical function), can be determined numerically though

In [8]:
norm.cdf(r)

array([ 0.93262414,  0.36949209,  0.67395072,  0.54227232,  0.20593594,
        0.45272479,  0.67384954,  0.21574201,  0.30548475,  0.1672512 ])

In [9]:
norm.logcdf(r)

array([-0.06975301, -0.99562595, -0.39459828, -0.61198696, -1.58019012,
       -0.79247085, -0.39474843, -1.53367201, -1.18585542, -1.78825839])