## Compare Lists vs Arrays

In [2]:
import numpy as np

In [12]:
L = [1,2,3]   # List
A = np.array([1,2,3])  # Numpy array

In [5]:
# Loop through
for e in L:
    print(e)

1
2
3


In [6]:
for e in A:
    print(e)

1
2
3


Both worked the same. 

Now append:

In [13]:
L.append(4)
L

[1, 2, 3, 4]

In [9]:
# Doesn't work with array
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [14]:
# Join lists
L = L + [5]
L

[1, 2, 3, 4, 5]

In [15]:
# Doesn't work with array
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [17]:
# Vector addition
# With Python List, using +, just appends to list (as above)
# Correct way:
L2 = []
for e in L:
    L2.append(e + e)

L2

[2, 4, 6, 8, 10]

In [19]:
A + A

array([2, 4, 6])

Plus sign in Python List, concatinates. Plus sign in numpy, adds

In [20]:
# Faster way:
2*A

array([2, 4, 6])

In [21]:
# Doesn't work with List, instead, duplicates list 
2 * L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [22]:
# Element wise squaring every element
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
# Correct way:
L2 = []
for e in L:
    L2.append(e*e)
    
L2

[1, 4, 9, 16, 25]

In [24]:
# Numpy:
A**2

array([1, 4, 9])

Most functions in numpy are elementwise

In [25]:
# Squareroot of all
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [26]:
# Log
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [27]:
#Exponential
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

To do the above in Lists, will need for loops