In [1]:
import numpy as np

Matrix: Two dimension array, or list of lists

In [3]:
M = np.array([[1,2],[3,4]])  # Must be the same size. 
L = [[1,2],[3,4]]

In [4]:
# Want to access a single element:
L[0][0] # List of lists

1

In [5]:
M[0][0] # Numpy matrix

1

In [6]:
# Can also do this:
M[0,0]

1

In [7]:
# Numpy "matrix" datatype
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [8]:
M

array([[1, 2],
       [3, 4]])

In [9]:
# Official Docs recomment using Array, NOT matrix
# Convert matrix to array
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [10]:
# Transpose:
A.T

array([[1, 3],
       [2, 4]])