In [1]:
import numpy as np

In [2]:
# passing in a list:
np.array([1,2])

array([1, 2])

In [3]:
# Array of all zeros
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
Z = np.zeros((10,10))
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
# All ones
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [8]:
# random array (these are all greater than 0 and less than 1)
R = np.random.random((10,10))
R   # Uniformly distrubted

array([[ 0.26090833,  0.89225468,  0.80116641,  0.51793686,  0.58579703,
         0.45780524,  0.80068285,  0.11202106,  0.14242014,  0.28829021],
       [ 0.69525956,  0.00657649,  0.89151691,  0.2708846 ,  0.07402912,
         0.78285222,  0.0939662 ,  0.60311681,  0.8625136 ,  0.76642852],
       [ 0.36918031,  0.16465367,  0.36646302,  0.73041969,  0.37021028,
         0.53209017,  0.95974486,  0.23263931,  0.20726621,  0.38670502],
       [ 0.79115513,  0.20599597,  0.6485552 ,  0.48174267,  0.87961686,
         0.82992325,  0.46069512,  0.27638839,  0.7453055 ,  0.48158078],
       [ 0.08931737,  0.45931106,  0.30353572,  0.23143776,  0.74751526,
         0.29180869,  0.26671601,  0.57320336,  0.18663448,  0.41467955],
       [ 0.43189772,  0.34271916,  0.54845965,  0.26044963,  0.06109091,
         0.26327381,  0.54151806,  0.70750334,  0.67154079,  0.18081076],
       [ 0.57162728,  0.7457949 ,  0.70314989,  0.11537896,  0.54686555,
         0.16350134,  0.98998753,  0.22336876

In [10]:
# Guassian distributed random (mean 0, variance 1)
G = np.random.randn(10, 10)   # This takes in each dimension as a single paramter, vs the tuple from above
G

array([[ -1.83098385e+00,  -1.22691599e+00,  -1.56913545e+00,
          1.43914221e-01,  -8.10243767e-01,   1.48718298e+00,
         -3.23091349e-01,  -2.62657687e-01,   1.04050813e+00,
         -9.01860891e-01],
       [ -1.15364195e-03,   7.13471798e-01,  -1.45462003e+00,
         -4.10485778e-01,  -5.02681030e-01,   1.09283313e+00,
          3.27471890e-01,  -5.00063082e-01,  -6.43462139e-01,
         -1.04885466e+00],
       [  1.02495910e+00,   5.60593905e-01,   2.29159315e-01,
          1.61328067e+00,  -5.40086963e-01,   6.75091453e-01,
         -7.35228901e-01,   1.31871973e+00,   2.05369455e-01,
         -2.22747223e-01],
       [  3.56012690e+00,   5.54924454e-01,   1.78056831e+00,
         -1.50076615e+00,  -1.98432522e+00,  -6.63640721e-01,
         -6.28670525e-01,  -7.60067628e-01,  -3.65495698e-01,
         -1.33531656e+00],
       [ -1.30695203e+00,  -9.71878431e-01,   7.11360230e-02,
          3.78981019e-01,  -1.08799571e+00,   1.01277078e+00,
          2.12791383e-01

In [11]:
G.mean()

-0.08076542996307419

In [12]:
G.var()

1.1818113065721219