In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4]])

In [6]:
# Matrix inverse (in the linalg module)
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
# Confirm above is correct by multiplying by dot product of A to get identity matrix which is
# 1 0
# 0 1
Ainv.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [10]:
# Matrix determinate
np.linalg.det(A)

-2.0000000000000004

In [11]:
# Diagonal of matric
np.diag(A)

array([1, 4])

In [12]:
# Create diagonal array when given something like above ^
np.diag([1,2])

array([[1, 0],
       [0, 2]])

If you pass in a 2D array to diag, you get a 1d array of the diagonal element. If you pass in a 1D array, you get a 2d array where all of the off elements are 0

In [13]:
# Outer product of two vectors
a = np.array([1,2])
b = np.array([3,4])

In [14]:
np.outer(a, b)

array([[3, 4],
       [6, 8]])

In [15]:
np.inner(a, b)

11

In [16]:
# Above is the same as dot product
a.dot(b)

11

In [19]:
# Matrix Trace:
np.diag(A).sum()

5

In [20]:
# Direct function
np.trace(A)

5

In [22]:
# Eigenvalues and eigenvectors
X = np.random.randn(100, 3)   # Each column is a feature (3), each row is a record

In [23]:
# Covariance:
cov = np.cov(X)
cov

array([[ 2.28538272, -0.69504495, -2.20018942, ...,  1.80437404,
         1.64668566, -0.16018164],
       [-0.69504495,  0.26690292,  0.44175012, ..., -0.82638866,
        -0.38253069,  0.13056913],
       [-2.20018942,  0.44175012,  3.04941648, ..., -0.60008806,
        -2.06966868, -0.18101698],
       ..., 
       [ 1.80437404, -0.82638866, -0.60008806, ...,  2.81287788,
         0.70870583, -0.53577124],
       [ 1.64668566, -0.38253069, -2.06966868, ...,  0.70870583,
         1.43841908,  0.05894592],
       [-0.16018164,  0.13056913, -0.18101698, ..., -0.53577124,
         0.05894592,  0.13190155]])

In [25]:
# Expect our share to be 3x3
# Remember to take the transpose when doing covariance?
cov = np.cov(X.T)
cov

array([[ 0.92404141, -0.10043646,  0.13608566],
       [-0.10043646,  0.87451599,  0.05474451],
       [ 0.13608566,  0.05474451,  1.26081272]])

In [27]:
np.linalg.eigh(cov)

(array([ 0.76197469,  0.98765634,  1.3097391 ]),
 array([[ 0.65565847, -0.68293694,  0.32203898],
        [ 0.7100496 ,  0.7027356 ,  0.04463455],
        [-0.25679084,  0.19939863,  0.94567365]]))

In [28]:
np.linalg.eig(cov)

(array([ 1.3097391 ,  0.76197469,  0.98765634]),
 array([[-0.32203898,  0.65565847, -0.68293694],
        [-0.04463455,  0.7100496 ,  0.7027356 ],
        [-0.94567365, -0.25679084,  0.19939863]]))